const BIT_SIZE = 32;
const BIT_NUM_PER_ROW = 24;
const SQUARES_PER_ROW = 40;
const BACKGROUND_POS_MAX = 640;
const LEVEL_BOUNDARY = 1216;

// arrow movements
const KEY_ARROW_UP = 38;
const KEY_ARROW_DOWN = 40;
const KEY_ARROW_LEFT = 37;
const KEY_ARROW_RIGHT = 39;

// directions
const DIRECTION_FRONT_RIGHT = "frontRight";
const DIRECTION_FRONT_STAND = "frontStand";
const DIRECTION_FRONT_LEFT = "frontLeft";
const DIRECTION_BACK_RIGHT = "backRight";
const DIRECTION_BACK_STAND = "backStand";
const DIRECTION_BACK_LEFT = "backLeft";
const DIRECTION_LEFT_RIGHT = "leftRight";
const DIRECTION_LEFT_STAND = "leftStand";
const DIRECTION_LEFT_LEFT = "leftLeft";
const DIRECTION_RIGHT_RIGHT = "rightRight";
const DIRECTION_RIGHT_STAND = "rightStand";
const DIRECTION_RIGHT_LEFT = "rightLeft";

export const CONSTANTS = {
	BIT_SIZE,
	BIT_NUM_PER_ROW,
	SQUARES_PER_ROW,
	BACKGROUND_POS_MAX,
	LEVEL_BOUNDARY,
	KEY_ARROW_UP,
	KEY_ARROW_DOWN,
	KEY_ARROW_LEFT,
	KEY_ARROW_RIGHT,
	DIRECTION_FRONT_RIGHT,
	DIRECTION_FRONT_STAND,
	DIRECTION_FRONT_LEFT,
	DIRECTION_BACK_RIGHT,
	DIRECTION_BACK_STAND,
	DIRECTION_BACK_LEFT,
	DIRECTION_LEFT_RIGHT,
	DIRECTION_LEFT_STAND,
	DIRECTION_LEFT_LEFT,
	DIRECTION_RIGHT_RIGHT,
	DIRECTION_RIGHT_STAND,
	DIRECTION_RIGHT_LEFT,
};

export default CONSTANTS;